### ISSUE TITLE
bug: update docs - --sarif-file must be relative path

### ISSUE THREAD

**Issue by tomwillis608** [tomwillis608/sarif-to-issue-action#100]
### Version

v1

### Current Behavior

If you pass a path with the github.workspace in the sarif-file argument, the file is not found.
It only works if you pass a relative path.

This *will not* work:
``yaml
      - name: Post SARIF findings in the issue
        uses: tomwillis608/sarif-to-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          sarif-file: ${{ github.workspace }}/test/fixtures/odc.sarif
          title: "Build artifact: issue-test.yml workflow"
          labels: "build,expected"
          dry-run: false
          odc-sarif: true
```

This will work:
```yaml
      - name: Post SARIF findings in the issue
        uses: tomwillis608/sarif-to-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: main
          sarif-file: ./test/fixtures/odc.sarif
          title: "Build artifact: issue-test.yml workflow"
          labels: "build,expected"
          dry-run: false
          odc-sarif: true
```

### Expected Behavior

Update docs so users enter the correct value for `sarif-file`

### Steps to Reproduce

If this is in your action:

``yaml
      - name: Post SARIF findings in the issue
        uses: tomwillis608/sarif-to-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          sarif-file: ${{ github.workspace }}/test/fixtures/odc.sarif
          title: "Build artifact: issue-test.yml workflow"
          labels: "build,expected"
          dry-run: false
          odc-sarif: true
```

The you will this error:

```console
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/work/owner/repo/test/fixtures/odc.sarif'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)

...

    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/owner/repo/test/fixtures/odc.sarif'
}
```
